//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.Hareket = new HashSet<Hareket>();
        }
    
        public int Id { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Lütfen sadece harf kullanınız.")]
        public string Ad { get; set; }
        [Required]
        public Nullable<byte> Kategori { get; set; }
        [Required]
        public Nullable<int> Yazar { get; set; }
        public string BasımYıl { get; set; }
        public string Yayinevi { get; set; }
        public string Sayfa { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hareket> Hareket { get; set; }
        public virtual Kategori Kategori1 { get; set; }
        public virtual Yazar Yazar1 { get; set; }
    }
}
