//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yorums()
        {
            this.Yorums1 = new HashSet<Yorums>();
        }
    
        public int Id { get; set; }
        public int YazarId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Icerik { get; set; }
        public int KitapId { get; set; }
        public Nullable<System.DateTime> YayinlanmaZamani { get; set; }
        public Nullable<System.DateTime> DegistirmeZamani { get; set; }
        public bool Durum { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorums> Yorums1 { get; set; }
        public virtual Yorums Yorums2 { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
